from django.core.management.base import BaseCommand
from apps.crops.models import Crop
from apps.market.models import MarketPrice
from apps.schemes.models import Scheme

CROPS = [
  {"name":"Rice","local_name":"Bhatta / Chawal / Akki / Biyyam","soil_types":["alluvial","clayey"],"ph_min":5.5,"ph_max":7.0,"temp_min":20,"temp_max":30,"rainfall_min":1200,"rainfall_max":2200,"humidity_min":80,"humidity_max":90,"n_min":60,"n_max":120,"p_min":30,"p_max":60,"k_min":30,"k_max":60,"suitable_regions":["Karnataka","Tamil Nadu","Andhra Pradesh","West Bengal","Punjab","Odisha"],"crop_calendar":{"Sowing":"June-July","Transplanting":"July-August","Harvesting":"October-November"},"cultivation_steps":"1. Prepare puddled field with 5cm standing water\n2. Select certified high-yield seeds\n3. Raise nursery for 25-30 days\n4. Transplant seedlings at 20x15cm spacing\n5. Maintain 2-5cm standing water\n6. Apply NPK fertilizer in 3 splits\n7. Control weeds at 20 and 40 days\n8. Monitor for blast and BLB disease\n9. Drain field 15 days before harvest\n10. Harvest at 80-85% grain maturity","water_needs":"High — 1200-2000mm. Maintain 5cm standing water throughout crop period.","disease_control":"Blast: Tricyclazole 0.6g/L. BLB: Copper Oxychloride 3g/L. Brown Spot: Mancozeb 2g/L."},
  {"name":"Wheat","local_name":"Gehun / Godhi / Godhuma","soil_types":["loamy","alluvial"],"ph_min":6.0,"ph_max":7.5,"temp_min":10,"temp_max":25,"rainfall_min":400,"rainfall_max":800,"humidity_min":50,"humidity_max":70,"n_min":80,"n_max":120,"p_min":40,"p_max":70,"k_min":40,"k_max":60,"suitable_regions":["Punjab","Haryana","Uttar Pradesh","Madhya Pradesh","Rajasthan","Bihar"],"crop_calendar":{"Sowing":"October-November","First Irrigation":"20-25 days","Harvesting":"March-April"},"cultivation_steps":"1. Deep ploughing after kharif harvest\n2. Two cross-harrowings for fine tilth\n3. Apply basal DAP and MOP\n4. Treat seed with Bavistin 2g/kg\n5. Sow in rows 22.5cm apart at 100kg/ha\n6. First irrigation at Crown Root Initiation stage\n7. Apply urea in 2 splits at CRI and tillering\n8. Weed control with Clodinafop 60g/ha\n9. Monitor for yellow rust and brown rust\n10. Harvest at golden yellow stage","water_needs":"Moderate — 400-650mm. 4-5 critical irrigations at CRI, tillering, jointing, flowering, milking.","disease_control":"Yellow Rust, Brown Rust: Propiconazole 25EC 0.1%. Loose Smut: Vitavax seed treatment 2g/kg."},
  {"name":"Maize","local_name":"Makka / Jola / Mokkajonna","soil_types":["loamy","alluvial","sandy"],"ph_min":5.8,"ph_max":7.0,"temp_min":18,"temp_max":32,"rainfall_min":500,"rainfall_max":1000,"humidity_min":55,"humidity_max":75,"n_min":60,"n_max":100,"p_min":30,"p_max":60,"k_min":20,"k_max":50,"suitable_regions":["Karnataka","Andhra Pradesh","Maharashtra","Bihar","Rajasthan","Madhya Pradesh"],"crop_calendar":{"Kharif Sowing":"June-July","Rabi Sowing":"October-November","Harvesting":"90-100 days after sowing"},"cultivation_steps":"1. Deep ploughing and 2-3 harrowings\n2. Apply FYM 10 tonnes/ha as basal\n3. Treat seeds with fungicide + insecticide\n4. Sow at 60x25cm spacing\n5. Apply basal NPK at sowing\n6. Thin to 1 plant per hill at 15 days\n7. Top-dress urea at knee-high stage\n8. Weed control at 20 and 40 days\n9. Scout for Fall Army Worm from 30 days\n10. Harvest when husks turn brown and dry","water_needs":"Moderate — 500-800mm. Very sensitive to waterlogging. Critical at tasseling and grain filling.","disease_control":"Fall Army Worm: Emamectin benzoate 5SG 0.4g/L. Turcicum Blight: Mancozeb 2g/L. Use resistant hybrids."},
  {"name":"Cotton","local_name":"Kapas / Hatti / Patti","soil_types":["black","loamy"],"ph_min":6.0,"ph_max":8.0,"temp_min":24,"temp_max":35,"rainfall_min":600,"rainfall_max":1200,"humidity_min":55,"humidity_max":80,"n_min":90,"n_max":120,"p_min":35,"p_max":60,"k_min":35,"k_max":60,"suitable_regions":["Gujarat","Maharashtra","Telangana","Karnataka","Haryana","Punjab"],"crop_calendar":{"Sowing":"May-June","Squaring":"60-65 days","Picking":"October-January"},"cultivation_steps":"1. Deep summer ploughing to 30cm\n2. Apply FYM and basal NPK fertilizer\n3. Treat Bt cotton seeds with fungicide\n4. Sow at 60x90cm or 45x90cm spacing\n5. Thin at 15 days to 1 plant per hill\n6. Inter-cultivation at 30 and 60 days\n7. Apply fertilizer in 3 splits\n8. Install pheromone traps 5 per acre\n9. Scout for bollworms from 45 days\n10. Pick cotton every 10-15 days when open","water_needs":"Moderate — 600-1000mm. Drought tolerant once established. Critical at flowering and boll formation.","disease_control":"Bollworm: Emamectin 0.4g/L. Wilt: use resistant Bt varieties. Sucking pests: Imidacloprid 0.3ml/L."},
  {"name":"Banana","local_name":"Kela / Bale / Arati / Vazhai","soil_types":["alluvial","loamy"],"ph_min":5.5,"ph_max":7.0,"temp_min":24,"temp_max":35,"rainfall_min":1200,"rainfall_max":2000,"humidity_min":70,"humidity_max":90,"n_min":90,"n_max":120,"p_min":55,"p_max":80,"k_min":35,"k_max":60,"suitable_regions":["Karnataka","Tamil Nadu","Andhra Pradesh","Maharashtra","Kerala","Gujarat"],"crop_calendar":{"Planting":"June-July or Feb-March","Bunch Emergence":"9-10 months","Harvesting":"10-12 months after planting"},"cultivation_steps":"1. Dig pits 45x45x45cm\n2. Fill with topsoil + FYM + neem cake\n3. Plant disease-free tissue culture plants\n4. Install drip irrigation at 8-10L/plant/day\n5. Apply weekly fertigation with NPK\n6. Desuckering — keep only 1 follower per plant\n7. Spray micronutrients at bunch emergence\n8. Prop bunch with bamboo poles\n9. Cover bunch with perforated polybag\n10. Harvest when fingers fill out (75-80% maturity)","water_needs":"High — 1200-2000mm equivalent. Drip recommended at 8-10L per plant per day.","disease_control":"Panama Wilt: use resistant varieties like Grand Naine. Sigatoka: Propiconazole 0.1%. Moko: field sanitation."},
  {"name":"Tomato","local_name":"Tamato / Solanum lycopersicum","soil_types":["loamy","red"],"ph_min":6.0,"ph_max":7.0,"temp_min":20,"temp_max":30,"rainfall_min":400,"rainfall_max":800,"humidity_min":60,"humidity_max":80,"n_min":60,"n_max":100,"p_min":40,"p_max":70,"k_min":40,"k_max":70,"suitable_regions":["Karnataka","Maharashtra","Andhra Pradesh","Tamil Nadu","Himachal Pradesh"],"crop_calendar":{"Nursery":"June-July or Oct-Nov","Transplanting":"25-30 days after sowing","Harvesting":"60-70 days after transplanting"},"cultivation_steps":"1. Prepare raised nursery beds 1m wide\n2. Sow seeds, cover with sand, water twice daily\n3. Transplant 25-30 day seedlings\n4. Stake plants when 30cm tall\n5. Install drip irrigation\n6. Apply weekly NPK fertigation\n7. Spray preventive fungicide every 10 days\n8. Harvest every 3-4 days when red","water_needs":"Moderate — drip recommended. 400-600mm total. Avoid water stress at flowering and fruit set.","disease_control":"Early/Late Blight: Mancozeb 2g/L every 10 days. Fusarium Wilt: resistant varieties + soil solarization."},
  {"name":"Onion","local_name":"Pyaz / Eerulli / Ullipayalu / Vengayam","soil_types":["loamy","alluvial"],"ph_min":6.0,"ph_max":7.0,"temp_min":13,"temp_max":25,"rainfall_min":350,"rainfall_max":650,"humidity_min":50,"humidity_max":70,"n_min":50,"n_max":80,"p_min":40,"p_max":70,"k_min":50,"k_max":80,"suitable_regions":["Maharashtra","Karnataka","Madhya Pradesh","Gujarat","Rajasthan","Bihar"],"crop_calendar":{"Nursery":"Oct-Nov (Rabi) / May-Jun (Kharif)","Transplanting":"6 weeks after sowing","Harvesting":"March-April / September-October"},"cultivation_steps":"1. Prepare raised beds 1.2m wide\n2. Apply FYM + NPK as basal dose\n3. Sow seeds at 5-6cm spacing\n4. Transplant 6-week seedlings at 15x10cm\n5. Apply potassium for good bulb development\n6. Irrigate every 7-10 days\n7. Stop irrigation 10 days before harvest\n8. Harvest when tops fall naturally\n9. Cure bulbs in shade for 10-15 days","water_needs":"Moderate — 350-500mm total. Avoid waterlogging. Drip irrigation preferred for quality bulbs.","disease_control":"Purple Blotch: Iprodione 0.2%. Thrips: Spinosad 0.5ml/L. Stemphylium: Mancozeb + Carbendazim."},
  {"name":"Sugarcane","local_name":"Ganna / Kabbu / Cheruku / Karumbu","soil_types":["alluvial","loamy","black"],"ph_min":6.0,"ph_max":7.5,"temp_min":24,"temp_max":38,"rainfall_min":1000,"rainfall_max":2000,"humidity_min":60,"humidity_max":85,"n_min":80,"n_max":120,"p_min":40,"p_max":70,"k_min":40,"k_max":80,"suitable_regions":["Uttar Pradesh","Maharashtra","Karnataka","Tamil Nadu","Punjab","Andhra Pradesh"],"crop_calendar":{"Planting":"Feb-March or Oct-Nov","Earthing Up":"60 and 120 days after planting","Harvesting":"12-18 months after planting"},"cultivation_steps":"1. Deep ploughing 45cm and FYM application\n2. Select healthy disease-free setts with 2-3 buds\n3. Treat setts with Carbendazim 0.1% for 30 minutes\n4. Plant in furrows at 90cm row spacing\n5. Cover setts with 5cm soil\n6. First irrigation immediately after planting\n7. Earthing up at 60 and 120 days\n8. Apply NPK fertilizer in 4 splits\n9. Propping at 6-7 months to prevent lodging\n10. Harvest at Brix 18-20% using refractometer","water_needs":"High — 1500-2500mm. Critical at germination, tillering, grand growth, and maturity stages.","disease_control":"Red Rot: disease-free setts, Carbendazim treatment. Smut: hot water treatment. Top Borer: Trichogramma release."},
  {"name":"Chickpea","local_name":"Chana / Kadale / Senagalu / Kadalai","soil_types":["loamy","red","black"],"ph_min":6.0,"ph_max":8.0,"temp_min":15,"temp_max":25,"rainfall_min":300,"rainfall_max":600,"humidity_min":30,"humidity_max":60,"n_min":20,"n_max":50,"p_min":50,"p_max":80,"k_min":30,"k_max":60,"suitable_regions":["Madhya Pradesh","Rajasthan","Uttar Pradesh","Maharashtra","Andhra Pradesh","Karnataka"],"crop_calendar":{"Sowing":"October-November","Flowering":"50-60 days","Harvesting":"90-110 days after sowing"},"cultivation_steps":"1. Deep ploughing and 2 harrowings\n2. Seed treatment with Rhizobium + Thiram\n3. Sow at 30x10cm spacing at 60-75kg/ha\n4. Apply only phosphorus as basal — no nitrogen needed\n5. One pre-sowing irrigation if soil is dry\n6. Weed control at 30 and 45 days\n7. Monitor for pod borer from 45 days\n8. Harvest when leaves turn yellow and pods rattle","water_needs":"Low — 300-450mm. One critical irrigation at flowering + pod filling stage.","disease_control":"Pod Borer: Emamectin 0.4g/L. Wilt: Carbendazim 1g/L soil drench. Blight: Mancozeb 2g/L."},
  {"name":"Mango","local_name":"Aam / Mavina Hannu / Mamidi / Maanga","soil_types":["alluvial","red","loamy"],"ph_min":5.5,"ph_max":7.5,"temp_min":24,"temp_max":38,"rainfall_min":600,"rainfall_max":1200,"humidity_min":45,"humidity_max":70,"n_min":15,"n_max":40,"p_min":15,"p_max":40,"k_min":35,"k_max":60,"suitable_regions":["Andhra Pradesh","Uttar Pradesh","Karnataka","Bihar","Gujarat","Maharashtra"],"crop_calendar":{"Flowering":"November-January","Fruiting":"February-April","Harvesting":"April-July"},"cultivation_steps":"1. Dig pits 1x1x1m and fill with FYM + topsoil\n2. Plant grafted plants at 10x10m spacing\n3. Irrigate young trees weekly\n4. Apply NPK fertilizer annually after bearing\n5. Prune dead branches every year\n6. Mango hopper and weevil control from flowering\n7. Harvest when skin color changes and fruit separates easily","water_needs":"Moderate — 600-1000mm. Needs dry spell before flowering. Critical irrigation at fruit development.","disease_control":"Anthracnose: Carbendazim 1g/L at flowering. Powdery Mildew: Sulphur 2g/L. Hopper: Imidacloprid 0.5ml/L."},
  {"name":"Coconut","local_name":"Nariyal / Tenga / Kobbari / Tengai","soil_types":["sandy","alluvial","laterite"],"ph_min":5.0,"ph_max":7.0,"temp_min":24,"temp_max":35,"rainfall_min":1200,"rainfall_max":2500,"humidity_min":65,"humidity_max":90,"n_min":30,"n_max":60,"p_min":15,"p_max":40,"k_min":35,"k_max":60,"suitable_regions":["Kerala","Tamil Nadu","Karnataka","Andhra Pradesh","Goa","Maharashtra"],"crop_calendar":{"Planting":"June-July or September-October","First Harvest":"6-8 years after planting","Peak Bearing":"15-20 years"},"cultivation_steps":"1. Dig pits 1x1x1m filled with FYM and topsoil\n2. Select high-yielding hybrid seedlings (12 months old)\n3. Plant at 7.5x7.5m spacing for square system\n4. Basin irrigation at 200L per tree per week\n5. Apply NPK + micronutrients every 6 months\n6. Green manure crops between palms\n7. Rhinoceros beetle control with pheromone traps\n8. Harvest nuts every 45-60 days","water_needs":"High — 1200-2500mm. Cannot tolerate drought. Drip irrigation at 200L/tree/week in dry season.","disease_control":"Rhinoceros Beetle: pheromone traps + Metarhizium spray. Leaf Rot: Bordeaux paste. Bud Rot: Copper Oxychloride."},
  {"name":"Coffee","local_name":"Kapi / Coffee / Kofi","soil_types":["laterite","red","loamy"],"ph_min":5.5,"ph_max":6.5,"temp_min":18,"temp_max":28,"rainfall_min":1500,"rainfall_max":2500,"humidity_min":55,"humidity_max":80,"n_min":90,"n_max":120,"p_min":15,"p_max":40,"k_min":25,"k_max":50,"suitable_regions":["Karnataka","Kerala","Tamil Nadu","Andhra Pradesh"],"crop_calendar":{"Pruning":"January-February","Flowering":"March-April","Harvesting":"October-January"},"cultivation_steps":"1. Plant shade trees (Silver Oak) before coffee\n2. Dig pits 45x45x45cm\n3. Plant seedlings at 2.7x2.7m spacing for Arabica\n4. Mulch with dry leaves to conserve moisture\n5. Apply NPK fertilizer twice a year\n6. Pruning annually to maintain bush shape\n7. Borer control with Endosulfan or neem oil\n8. Harvest ripe red berries selectively (selective picking)","water_needs":"High — 1500-2500mm. Shade growing conserves moisture. Critical at flowering and berry development.","disease_control":"White Stem Borer: Endosulfan soil drench. Berry Borer: Beauveria bassiana spray. Leaf Rust: Copper hydroxide."},
  {"name":"Groundnut","local_name":"Moongphali / Kadalekai / Pallelu / Verkadalai","soil_types":["sandy","loamy","red"],"ph_min":5.5,"ph_max":7.0,"temp_min":20,"temp_max":35,"rainfall_min":500,"rainfall_max":1200,"humidity_min":50,"humidity_max":75,"n_min":20,"n_max":40,"p_min":40,"p_max":60,"k_min":20,"k_max":40,"suitable_regions":["Gujarat","Andhra Pradesh","Rajasthan","Tamil Nadu","Karnataka","Maharashtra"],"crop_calendar":{"Sowing":"June-July (Kharif) / January-February (Rabi)","Pegging":"40-50 days","Harvesting":"100-120 days"},"cultivation_steps":"1. Plough and harrow to fine tilth\n2. Apply gypsum 500kg/ha as basal\n3. Seed treatment with Rhizobium + Thiram\n4. Sow at 30x10cm spacing\n5. Weeding at 25 and 45 days\n6. Apply gypsum again at pegging stage\n7. Maintain optimum moisture at pegging\n8. Harvest when leaves yellow and inner shell shows dark markings\n9. Dry pods in sun for 3-4 days","water_needs":"Moderate — 500-700mm. Critical at flowering and pegging. Avoid waterlogging.","disease_control":"Leaf Spot: Mancozeb 2g/L at 30, 45, 60 days. Rust: same. Tikka: Chlorothalonil 2g/L."},
  {"name":"Soybean","local_name":"Soya / Soyabean","soil_types":["loamy","black","alluvial"],"ph_min":6.0,"ph_max":7.5,"temp_min":20,"temp_max":32,"rainfall_min":600,"rainfall_max":1000,"humidity_min":55,"humidity_max":80,"n_min":25,"n_max":50,"p_min":40,"p_max":70,"k_min":30,"k_max":50,"suitable_regions":["Madhya Pradesh","Maharashtra","Rajasthan","Karnataka","Andhra Pradesh"],"crop_calendar":{"Sowing":"June-July","Podding":"60-70 days","Harvesting":"90-100 days"},"cultivation_steps":"1. Plough and add FYM before sowing\n2. Seed treatment with Rhizobium + Thiram\n3. Sow at 45x5cm spacing at 70-80kg/ha\n4. Apply only phosphorus and potassium as basal\n5. Weeding at 20 and 40 days\n6. Monitor for semilooper and girdle beetle\n7. Harvest when 95% pods are brown","water_needs":"Moderate — 600-900mm. Critical at flowering and pod filling. Avoid standing water.","disease_control":"Yellow Mosaic: Imidacloprid for whitefly vector. Pod Borer: Quinalphos 1.5ml/L. Rust: Propiconazole 1ml/L."},
  {"name":"Jute","local_name":"Pat / Nalita / Juttu","soil_types":["alluvial","loamy"],"ph_min":6.0,"ph_max":7.5,"temp_min":24,"temp_max":38,"rainfall_min":1200,"rainfall_max":2500,"humidity_min":65,"humidity_max":90,"n_min":50,"n_max":80,"p_min":35,"p_max":60,"k_min":35,"k_max":60,"suitable_regions":["West Bengal","Bihar","Odisha","Assam","Uttar Pradesh"],"crop_calendar":{"Sowing":"March-May","Weeding":"25-30 days","Retting":"100-120 days"},"cultivation_steps":"1. Plough and harrow twice\n2. Sow at 25-30 cm row spacing\n3. Thin seedlings at 10-15 days\n4. Apply NPK fertilizer at sowing\n5. Weed control at 25 days\n6. Cut at 50% flowering stage for quality fibre\n7. Ret in slow-running water for 15-20 days\n8. Strip fibre and dry in sun","water_needs":"High — 1200-2500mm. Requires abundant moisture throughout growth. Alluvial floodplain soils ideal.","disease_control":"Stem Rot: Carbendazim 1g/L. Leaf Spot: Mancozeb 2g/L. Semilooper: Malathion 1ml/L."},
  {"name":"Lentil","local_name":"Masoor / Masure / Misur / Masuri","soil_types":["loamy","alluvial","sandy"],"ph_min":6.0,"ph_max":8.0,"temp_min":12,"temp_max":25,"rainfall_min":300,"rainfall_max":600,"humidity_min":35,"humidity_max":60,"n_min":10,"n_max":30,"p_min":55,"p_max":80,"k_min":15,"k_max":40,"suitable_regions":["Uttar Pradesh","Madhya Pradesh","Bihar","West Bengal","Rajasthan"],"crop_calendar":{"Sowing":"October-November","Flowering":"60-70 days","Harvesting":"100-110 days"},"cultivation_steps":"1. Plough to fine tilth\n2. Treat seeds with Rhizobium\n3. Sow at 30x10cm spacing at 35-40kg/ha\n4. Apply phosphorus as basal — no nitrogen\n5. Weed once at 30 days\n6. Protect from frost in December-January\n7. Harvest when lower pods turn yellow","water_needs":"Low — 300-450mm. One irrigation at flowering if soil is dry. Drought tolerant.","disease_control":"Rust: Mancozeb 2g/L. Blight: Zineb 2g/L. Pod Borer: Quinalphos 1.5ml/L."},
  {"name":"Mungbean","local_name":"Moong / Hesarukalu / Pesalu / Payiru","soil_types":["loamy","sandy","alluvial"],"ph_min":6.0,"ph_max":7.5,"temp_min":24,"temp_max":35,"rainfall_min":500,"rainfall_max":900,"humidity_min":55,"humidity_max":80,"n_min":15,"n_max":40,"p_min":35,"p_max":60,"k_min":15,"k_max":40,"suitable_regions":["Rajasthan","Maharashtra","Andhra Pradesh","Karnataka","Uttar Pradesh"],"crop_calendar":{"Sowing":"June-July or February-March","Flowering":"35-40 days","Harvesting":"60-70 days"},"cultivation_steps":"1. One ploughing and two harrowings\n2. Seed treatment with Rhizobium + Thiram\n3. Sow at 30x10cm at 15-20kg/ha\n4. Apply phosphorus and potassium as basal\n5. Weed at 20-25 days\n6. Harvest pods as they mature (2-3 pickings)\n7. Dry and thresh","water_needs":"Moderate — 500-700mm. Drought tolerant. One irrigation at flowering if dry.","disease_control":"Yellow Mosaic: Imidacloprid for whitefly. Cercospora Leaf Spot: Mancozeb 2g/L. Pod Borer: Quinalphos."},
  {"name":"Blackgram","local_name":"Urad / Uddina / Minumulu / Ulundu","soil_types":["loamy","alluvial","black"],"ph_min":5.5,"ph_max":7.5,"temp_min":24,"temp_max":35,"rainfall_min":600,"rainfall_max":1000,"humidity_min":55,"humidity_max":80,"n_min":30,"n_max":60,"p_min":50,"p_max":80,"k_min":15,"k_max":40,"suitable_regions":["Andhra Pradesh","Tamil Nadu","Uttar Pradesh","Maharashtra","Karnataka"],"crop_calendar":{"Sowing":"June-July","Flowering":"45-50 days","Harvesting":"70-80 days"},"cultivation_steps":"1. Plough twice and harrow\n2. Rhizobium + Thiram seed treatment\n3. Sow at 30x10cm at 15-20kg/ha\n4. Apply phosphorus as basal\n5. Weed at 20-25 days\n6. Harvest when 80% pods are black/mature\n7. Sun dry and thresh","water_needs":"Moderate — 600-800mm. Sensitive to waterlogging. One protective irrigation at flowering.","disease_control":"Yellow Mosaic Virus: Monocrotophos. Cercospora Leaf Spot: Mancozeb 2g/L. Pod Borer: Chlorpyriphos."},
  {"name":"Papaya","local_name":"Papita / Parangi / Boppayi / Pappali","soil_types":["alluvial","loamy","red"],"ph_min":5.5,"ph_max":7.0,"temp_min":24,"temp_max":38,"rainfall_min":1000,"rainfall_max":2000,"humidity_min":65,"humidity_max":85,"n_min":40,"n_max":70,"p_min":40,"p_max":70,"k_min":40,"k_max":70,"suitable_regions":["Karnataka","Andhra Pradesh","Tamil Nadu","Maharashtra","Gujarat","Bihar"],"crop_calendar":{"Planting":"February-March or September-October","Flowering":"5-7 months","Harvesting":"9-11 months after planting"},"cultivation_steps":"1. Dig pits 50x50x50cm with FYM\n2. Plant 3 seedlings per pit initially\n3. Remove extra plants keeping best one\n4. Drip or basin irrigation twice weekly\n5. Apply NPK monthly\n6. Remove male plants (keep 10% for pollination)\n7. Support heavy bearing stems\n8. Harvest when skin turns yellowish","water_needs":"Moderate-High — 1000-1500mm. Drip irrigation preferred. Cannot tolerate waterlogging.","disease_control":"Papaya Ring Spot Virus: use virus-free seedlings, control aphids. Anthracnose: Mancozeb 2g/L. Powdery Mildew: Sulphur."},
  {"name":"Grapes","local_name":"Angur / Drakshi / Drakshe / Thirakshai","soil_types":["loamy","sandy","red"],"ph_min":5.5,"ph_max":7.0,"temp_min":18,"temp_max":30,"rainfall_min":600,"rainfall_max":1000,"humidity_min":55,"humidity_max":80,"n_min":15,"n_max":40,"p_min":15,"p_max":40,"k_min":15,"k_max":40,"suitable_regions":["Maharashtra","Karnataka","Andhra Pradesh","Tamil Nadu","Punjab"],"crop_calendar":{"Pruning":"October-November","Flowering":"January-February","Harvesting":"March-May"},"cultivation_steps":"1. Install trellis or bower system\n2. Plant rooted cuttings at 3x3m spacing\n3. Train vines on support system\n4. Two prunings per year — cane and spur pruning\n5. Drip irrigation at 20-30L/vine/day\n6. Fertigation weekly with NPK\n7. Bag clusters for quality and pest control\n8. Harvest at Brix 18-22%","water_needs":"Moderate — 600-900mm. Drip irrigation essential. Dry weather during ripening improves sugar.","disease_control":"Powdery Mildew: Sulphur 2g/L every 10 days. Downy Mildew: Mancozeb 2g/L. Anthracnose: Carbendazim 1g/L."},
  {"name":"Watermelon","local_name":"Tarbooz / Kallangadi / Puccha Kaya / Tarbuzh","soil_types":["sandy","loamy","red"],"ph_min":5.5,"ph_max":7.0,"temp_min":24,"temp_max":35,"rainfall_min":400,"rainfall_max":800,"humidity_min":55,"humidity_max":80,"n_min":70,"n_max":100,"p_min":35,"p_max":60,"k_min":35,"k_max":60,"suitable_regions":["Karnataka","Andhra Pradesh","Tamil Nadu","Maharashtra","Rajasthan","Uttar Pradesh"],"crop_calendar":{"Sowing":"February-March or June-July","Flowering":"30-40 days","Harvesting":"70-90 days"},"cultivation_steps":"1. Prepare raised beds with FYM\n2. Sow 2 seeds per pit at 2x2m spacing\n3. Thin to 1 plant per pit at 7 days\n4. Apply basal NPK fertilizer\n5. Install drip irrigation\n6. Mulch with plastic or straw\n7. Pollinate manually if bee activity is low\n8. Harvest when tendril near fruit dries and sound is hollow","water_needs":"Moderate — 400-600mm. Drip irrigation preferred. Avoid excess moisture during ripening.","disease_control":"Downy Mildew: Mancozeb 2g/L. Anthracnose: Carbendazim 1g/L. Fruit Fly: bait traps."},
  {"name":"Orange","local_name":"Santra / Kittale / Nimmakaya / Kamala","soil_types":["alluvial","loamy","red"],"ph_min":5.5,"ph_max":7.0,"temp_min":18,"temp_max":30,"rainfall_min":600,"rainfall_max":1200,"humidity_min":55,"humidity_max":80,"n_min":15,"n_max":40,"p_min":8,"p_max":20,"k_min":8,"k_max":20,"suitable_regions":["Maharashtra","Andhra Pradesh","Punjab","Rajasthan","Karnataka","Assam"],"crop_calendar":{"Planting":"June-July","Flowering":"September-October","Harvesting":"January-March"},"cultivation_steps":"1. Dig pits 60x60x60cm with FYM\n2. Plant budded plants at 6x6m spacing\n3. Basin irrigation at 100-150L per tree\n4. Apply NPK twice a year\n5. Light pruning to remove dead wood\n6. Zinc and iron spray to prevent deficiency\n7. Harvest at full colour development","water_needs":"Moderate — 600-1000mm. Needs summer irrigation. Critical at fruit development stage.","disease_control":"Citrus Canker: Bordeaux mixture 1%. Scab: Carbendazim 1g/L. Psylla: Monocrotophos 1.5ml/L."},
  {"name":"Apple","local_name":"Seb / Simasameni / Mahali / Malus","soil_types":["loamy","alluvial"],"ph_min":5.5,"ph_max":6.5,"temp_min":8,"temp_max":20,"rainfall_min":800,"rainfall_max":1500,"humidity_min":55,"humidity_max":80,"n_min":15,"n_max":40,"p_min":8,"p_max":20,"k_min":35,"k_max":60,"suitable_regions":["Himachal Pradesh","Jammu & Kashmir","Uttarakhand","Arunachal Pradesh"],"crop_calendar":{"Dormancy Pruning":"December-January","Flowering":"March-April","Harvesting":"August-October"},"cultivation_steps":"1. Prepare terraced land on hillslopes\n2. Plant on rootstock at 6x6m spacing\n3. Train to spindle bush or central leader form\n4. Annual pruning during dormancy\n5. Apply NPK in 3 splits: March, June, August\n6. Hail netting essential in hilly regions\n7. Thin fruits at marble size (1 fruit per spur)\n8. Harvest at 135-140 days after full bloom","water_needs":"Moderate — 800-1200mm. Adequate snowfall in winter important. Summer irrigation in dry spells.","disease_control":"Scab: Mancozeb 2g/L from bud burst. Fire Blight: Streptomycin at bloom. Codling Moth: Chlorpyriphos."},
]

MARKET = [
  ("Rice","grain","Karnataka","Bangalore Rural","APMC Bangalore",1800,2200,2050,"high"),
  ("Rice","grain","Tamil Nadu","Thanjavur","Thanjavur APMC",1750,2100,1980,"high"),
  ("Rice","grain","Andhra Pradesh","Krishna","Krishna APMC",1700,2050,1900,"high"),
  ("Rice","grain","West Bengal","Hooghly","Hooghly Market",1650,2000,1850,"high"),
  ("Rice","grain","Punjab","Amritsar","Amritsar Mandi",1800,2150,2000,"high"),
  ("Wheat","grain","Punjab","Amritsar","Amritsar Mandi",2100,2400,2250,"moderate"),
  ("Wheat","grain","Haryana","Karnal","Karnal Mandi",2050,2350,2200,"moderate"),
  ("Wheat","grain","Uttar Pradesh","Agra","Agra Mandi",2000,2300,2150,"moderate"),
  ("Wheat","grain","Madhya Pradesh","Bhopal","Bhopal Mandi",1980,2280,2130,"moderate"),
  ("Maize","grain","Karnataka","Tumkur","Tumkur APMC",1600,1900,1750,"moderate"),
  ("Maize","grain","Andhra Pradesh","Guntur","Guntur APMC",1550,1850,1700,"moderate"),
  ("Maize","grain","Bihar","Patna","Patna Mandi",1500,1800,1650,"moderate"),
  ("Cotton","grain","Gujarat","Rajkot","Rajkot Mandi",6200,6800,6500,"high"),
  ("Cotton","grain","Maharashtra","Akola","Akola APMC",6000,6600,6300,"high"),
  ("Cotton","grain","Telangana","Warangal","Warangal APMC",6100,6700,6400,"high"),
  ("Cotton","grain","Karnataka","Dharwad","Dharwad APMC",6050,6650,6350,"high"),
  ("Sugarcane","grain","Karnataka","Mandya","Mandya APMC",280,310,295,"high"),
  ("Sugarcane","grain","Uttar Pradesh","Meerut","Meerut Mandi",290,320,305,"high"),
  ("Sugarcane","grain","Maharashtra","Kolhapur","Kolhapur APMC",285,315,300,"high"),
  ("Tomato","vegetable","Karnataka","Kolar","Kolar Market",800,1400,1100,"moderate"),
  ("Tomato","vegetable","Maharashtra","Pune","Pune APMC",750,1300,1050,"moderate"),
  ("Tomato","vegetable","Andhra Pradesh","Chittoor","Chittoor APMC",700,1200,1000,"moderate"),
  ("Tomato","vegetable","Himachal Pradesh","Shimla","Shimla Market",900,1600,1250,"high"),
  ("Onion","vegetable","Maharashtra","Nashik","Nashik APMC",1000,1600,1300,"high"),
  ("Onion","vegetable","Karnataka","Hubli","Hubli APMC",900,1500,1200,"high"),
  ("Onion","vegetable","Rajasthan","Alwar","Alwar Mandi",850,1450,1150,"high"),
  ("Potato","vegetable","Uttar Pradesh","Agra","Agra Mandi",900,1200,1050,"moderate"),
  ("Potato","vegetable","West Bengal","Hooghly","Hooghly Market",850,1150,1000,"moderate"),
  ("Potato","vegetable","Punjab","Jalandhar","Jalandhar Mandi",870,1170,1020,"moderate"),
  ("Capsicum","vegetable","Karnataka","Mysore","Mysore Market",2000,3000,2500,"moderate"),
  ("Brinjal","vegetable","Karnataka","Hassan","Hassan Market",600,1000,800,"low"),
  ("Cabbage","vegetable","Karnataka","Bengaluru","APMC Bengaluru",500,900,700,"low"),
  ("Cauliflower","vegetable","Maharashtra","Nashik","Nashik APMC",600,1100,850,"moderate"),
  ("Okra","vegetable","Andhra Pradesh","Hyderabad","Hyderabad Market",1200,1800,1500,"moderate"),
  ("Peas","vegetable","Himachal Pradesh","Shimla","Shimla Market",3000,4500,3800,"high"),
  ("Banana","fruit","Tamil Nadu","Thanjavur","Thanjavur Market",1200,1800,1500,"high"),
  ("Banana","fruit","Karnataka","Tumkur","Tumkur Market",1100,1700,1400,"high"),
  ("Banana","fruit","Andhra Pradesh","Krishna","Krishna Market",1150,1750,1450,"high"),
  ("Mango","fruit","Andhra Pradesh","Krishna","Krishna APMC",2000,3500,2800,"high"),
  ("Mango","fruit","Maharashtra","Ratnagiri","Ratnagiri Market",3000,5000,4000,"high"),
  ("Mango","fruit","Karnataka","Kolar","Kolar Market",1800,3000,2500,"high"),
  ("Mango","fruit","Uttar Pradesh","Lucknow","Lucknow Mandi",1500,2800,2200,"high"),
  ("Grapes","fruit","Maharashtra","Nasik","Nasik APMC",4000,6000,5000,"moderate"),
  ("Grapes","fruit","Karnataka","Bijapur","Bijapur Market",3500,5500,4500,"moderate"),
  ("Pomegranate","fruit","Maharashtra","Solapur","Solapur Market",5000,8000,6500,"moderate"),
  ("Papaya","fruit","Karnataka","Bengaluru","APMC Bengaluru",800,1200,1000,"moderate"),
  ("Coconut","fruit","Kerala","Thrissur","Thrissur Market",2500,3500,3000,"high"),
  ("Coconut","fruit","Karnataka","Tumkur","Tumkur Market",2200,3200,2700,"high"),
  ("Coconut","fruit","Tamil Nadu","Coimbatore","Coimbatore Market",2300,3300,2800,"high"),
  ("Watermelon","fruit","Karnataka","Kolar","Kolar Market",300,600,450,"moderate"),
  ("Orange","fruit","Maharashtra","Nagpur","Nagpur Market",3000,5000,4000,"high"),
  ("Apple","fruit","Himachal Pradesh","Shimla","Shimla Market",7000,12000,9500,"high"),
  ("Groundnut","grain","Gujarat","Rajkot","Rajkot Mandi",5500,6500,6000,"moderate"),
  ("Groundnut","grain","Andhra Pradesh","Kurnool","Kurnool APMC",5000,6000,5500,"moderate"),
  ("Soybean","grain","Madhya Pradesh","Indore","Indore Mandi",4200,4800,4500,"moderate"),
  ("Soybean","grain","Maharashtra","Latur","Latur APMC",4100,4700,4400,"moderate"),
  ("Chickpea","grain","Madhya Pradesh","Indore","Indore Mandi",5000,5800,5400,"moderate"),
  ("Chickpea","grain","Rajasthan","Jaipur","Jaipur Mandi",4800,5600,5200,"moderate"),
  ("Lentil","grain","Uttar Pradesh","Lucknow","Lucknow Mandi",5500,6500,6000,"moderate"),
  ("Coffee","grain","Karnataka","Chikkamagaluru","Chikkamagaluru Market",32000,40000,36000,"high"),
]

SCHEMES = [
  {"title":"PM-KISAN","description":"Pradhan Mantri Kisan Samman Nidhi — Direct income support to all landholding farmer families across India.","ministry":"Ministry of Agriculture & Farmers Welfare","state":"","benefit":"₹6,000 per year in 3 installments of ₹2,000 directly to bank account.","eligibility":"All landholding farmer families with cultivable land.","apply_link":"https://pmkisan.gov.in","budget_crore":60000,"category":"Income Support"},
  {"title":"Pradhan Mantri Fasal Bima Yojana (PMFBY)","description":"Comprehensive crop insurance covering pre-sowing to post-harvest losses due to natural calamities.","ministry":"Ministry of Agriculture & Farmers Welfare","state":"","benefit":"Full insurance coverage for crop losses. Farmer premium only 1.5-2%.","eligibility":"All farmers growing notified crops. Compulsory for loanee farmers.","apply_link":"https://pmfby.gov.in","budget_crore":15500,"category":"Insurance"},
  {"title":"Kisan Credit Card (KCC)","description":"Easy short-term credit facility for farmers at subsidised interest rates.","ministry":"Ministry of Finance / NABARD","state":"","benefit":"Crop loans at just 4% interest per year (after interest subvention).","eligibility":"All farmers, sharecroppers, oral lessees, and tenant farmers.","apply_link":"https://www.nabard.org","budget_crore":0,"category":"Credit"},
  {"title":"PM Krishi Sinchayee Yojana (PMKSY)","description":"Har Khet Ko Pani — drip and sprinkler irrigation subsidy for every farm.","ministry":"Ministry of Jal Shakti","state":"","benefit":"55% subsidy on drip/sprinkler systems (75% for SC/ST/small farmers).","eligibility":"All farmers with agricultural land.","apply_link":"https://pmksy.gov.in","budget_crore":50000,"category":"Irrigation"},
  {"title":"Soil Health Card Scheme","description":"Free soil testing and crop-wise fertilizer recommendations every 2 years.","ministry":"Ministry of Agriculture & Farmers Welfare","state":"","benefit":"Free soil health card with complete nutrient status and precise recommendations.","eligibility":"All farmers across India.","apply_link":"https://soilhealth.dac.gov.in","budget_crore":368,"category":"Soil Health"},
  {"title":"e-NAM (National Agriculture Market)","description":"Online trading platform connecting farmers to buyers at 1000+ mandis across India.","ministry":"Ministry of Agriculture & Farmers Welfare","state":"","benefit":"Better price discovery, transparent bidding, direct bank payment to farmer.","eligibility":"All farmers with Aadhaar and bank account registered at e-NAM mandi.","apply_link":"https://enam.gov.in","budget_crore":200,"category":"Market Access"},
  {"title":"PM Kisan Maan Dhan Yojana","description":"Voluntary pension scheme for small and marginal farmers after age 60.","ministry":"Ministry of Agriculture & Farmers Welfare","state":"","benefit":"₹3,000 per month guaranteed pension after age 60.","eligibility":"Small and marginal farmers aged 18-40 with up to 2 hectares land.","apply_link":"https://maandhan.in/farmer","budget_crore":10774,"category":"Pension"},
  {"title":"Raitha Siri (Karnataka)","description":"Karnataka state direct income support scheme for registered farmers every season.","ministry":"Agriculture Department Karnataka","state":"Karnataka","benefit":"₹2,000 per acre per season (maximum 2 acres = ₹4,000/season).","eligibility":"All registered farmers in Karnataka with valid RTC land records.","apply_link":"https://raitamitra.karnataka.gov.in","budget_crore":3000,"category":"Income Support"},
  {"title":"Rythu Bandhu (Telangana)","description":"Telangana investment support scheme per season per acre for all farmers.","ministry":"Agriculture Department Telangana","state":"Telangana","benefit":"₹5,000 per acre per season for both Kharif and Rabi — paid before sowing.","eligibility":"All farmers in Telangana with valid land records (pattadar passbooks).","apply_link":"https://rythubandhu.telangana.gov.in","budget_crore":12000,"category":"Income Support"},
  {"title":"Mukhyamantri Kisan Kalyan Yojana (MP)","description":"Madhya Pradesh additional income support scheme over and above PM-KISAN.","ministry":"Agriculture Department Madhya Pradesh","state":"Madhya Pradesh","benefit":"₹4,000 per year extra (total ₹10,000/year with PM-KISAN).","eligibility":"All PM-KISAN beneficiaries in Madhya Pradesh.","apply_link":"https://saara.mp.gov.in","budget_crore":3200,"category":"Income Support"},
]

class Command(BaseCommand):
    help = 'Seed all data — crops (23), market prices (59), schemes (10)'

    def handle(self, *args, **kwargs):
        self.stdout.write(self.style.HTTP_INFO('\n🌱 Seeding AGRO_ADV database...\n'))

        self.stdout.write('Seeding 23 crops...')
        created_crops = 0
        for c in CROPS:
            _, created = Crop.objects.get_or_create(name=c['name'], defaults=c)
            if created:
                created_crops += 1
        self.stdout.write(self.style.SUCCESS(f'  ✓ {Crop.objects.count()} crops total ({created_crops} new)'))

        self.stdout.write('Seeding market prices...')
        for crop, cat, state, district, market, mn, mx, modal, demand in MARKET:
            MarketPrice.objects.update_or_create(
                crop_name=crop, market=market, state=state,
                defaults={'category':cat,'district':district,'min_price':mn,'max_price':mx,'modal_price':modal,'demand':demand}
            )
        self.stdout.write(self.style.SUCCESS(f'  ✓ {MarketPrice.objects.count()} market price records'))

        self.stdout.write('Seeding government schemes...')
        for s in SCHEMES:
            Scheme.objects.get_or_create(title=s['title'], defaults=s)
        self.stdout.write(self.style.SUCCESS(f'  ✓ {Scheme.objects.count()} schemes'))

        self.stdout.write(self.style.SUCCESS('\n✅ Seeding complete!\n'))
        self.stdout.write('Run: python manage.py runserver\n')
        self.stdout.write('Open: http://127.0.0.1:8000\n')
