# Generated by Django 5.0.4 on 2026-04-17 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('ministry', models.CharField(blank=True, max_length=200)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('benefit', models.TextField()),
                ('eligibility', models.TextField(blank=True)),
                ('apply_link', models.URLField(blank=True)),
                ('budget_crore', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('category', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
