# Generated by Django 5.0.4 on 2026-04-17 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('local_name', models.CharField(blank=True, max_length=200)),
                ('soil_types', models.JSONField(default=list)),
                ('ph_min', models.FloatField(default=5.5)),
                ('ph_max', models.FloatField(default=7.5)),
                ('temp_min', models.FloatField(default=20.0)),
                ('temp_max', models.FloatField(default=35.0)),
                ('rainfall_min', models.FloatField(default=500.0)),
                ('rainfall_max', models.FloatField(default=1500.0)),
                ('humidity_min', models.FloatField(default=40.0)),
                ('humidity_max', models.FloatField(default=90.0)),
                ('n_min', models.FloatField(default=20.0)),
                ('n_max', models.FloatField(default=120.0)),
                ('p_min', models.FloatField(default=20.0)),
                ('p_max', models.FloatField(default=80.0)),
                ('k_min', models.FloatField(default=20.0)),
                ('k_max', models.FloatField(default=80.0)),
                ('cultivation_steps', models.TextField(blank=True)),
                ('water_needs', models.TextField(blank=True)),
                ('disease_control', models.TextField(blank=True)),
                ('suitable_regions', models.JSONField(default=list)),
                ('crop_calendar', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
